global using CasCap.Common.Extensions;
global using CasCap.Common.Xunit;
global using CasCap.Models;
global using CasCap.Services;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System.Diagnostics;
global using Xunit;
