<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CasCap.Common.Net" Version="4.12.3" />
    <PackageVersion Include="CasCap.Common.Testing" Version="4.12.3" />
    <PackageVersion Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageVersion Include="Google.Apis.IAMCredentials.v1" Version="1.75.0.4198" />
    <PackageVersion Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.9.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" />
    <PackageVersion Include="MimeTypeMapOfficial" Version="1.0.17" />
    <PackageVersion Include="System.Linq.Async" Version="7.0.1" />
    <PackageVersion Include="System.Text.Json" Version="10.0.11" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>
</Project>