<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <Description>.NET client library for the Google Photos Library and Picker APIs.</Description>
    <PackageDescription>
      $(Description)

      This unofficial library manages application-created media and albums through the Library API and accesses
      user-selected existing media through the Picker API.

      The library leverages the authentication in the official Google.Apis.Auth library and builds on that
      by encapsulating all REST API calls in an efficient wrapper returning strongly-typed objects.

      For more details about the underlying API see the official site, https://developers.google.com/photos

      For usage examples see the docs on github, https://github.com/f2calv/CasCap.Api.GooglePhotos
    </PackageDescription>
    <PackageTags>google, photos, rest, api, wrapper</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="MimeTypeMapOfficial" />
    <PackageReference Include="System.Threading.RateLimiting" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CasCap.Api.GooglePhotos.Tests" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='Debug'">
    <ProjectReference Include="..\..\..\CasCap.Common\src\CasCap.Common.Net\CasCap.Common.Net.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)'=='Release'">
    <PackageReference Include="CasCap.Common.Net" />
  </ItemGroup>

</Project>
