name: ci

on:
  workflow_dispatch:
    inputs:
      configuration:
        type: choice
        description: Build Configuration
        required: true
        default: Release
        options:
          - Release
          - Debug
      push-preview:
        type: string
        description: Push preview branch?
        required: true
        default: "false"
  push:
    branches-ignore:
      - "preview/**"
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  lint:
    uses: f2calv/gha-workflows/.github/workflows/lint.yml@v1

  versioning:
    uses: f2calv/gha-workflows/.github/workflows/gha-release-versioning.yml@v1
    with:
      tag-prefix: ''
      tag-and-release: false

  build:
    runs-on: ubuntu-latest
    needs: [versioning]
    steps:
      - name: debugging
        run: |
          pwd
          '${{ secrets.GOOGLE_PHOTOS_TOKEN_RESPONSE }}' | base64 --decode | jq > Google.Apis.Auth.OAuth2.Responses.TokenResponse-${{ secrets.GOOGLE_PHOTOS_EMAIL }}.json

          cat Google.Apis.Auth.OAuth2.Responses.TokenResponse-${{ secrets.GOOGLE_PHOTOS_EMAIL }}.json

      # - uses: f2calv/gha-dotnet-nuget@v2
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      #     configuration: ${{ inputs.configuration }}
      #     push-preview: ${{ inputs.push-preview }}
      #     version: ${{ needs.versioning.outputs.version }}
      #   env:
      #     CasCap__GooglePhotosOptions__User: ${{ secrets.GOOGLE_PHOTOS_EMAIL }}
      #     CasCap__GooglePhotosOptions__ClientId: ${{ secrets.GOOGLE_PHOTOS_CLIENTID }}
      #     CasCap__GooglePhotosOptions__ClientSecret: ${{ secrets.GOOGLE_PHOTOS_SECRET }}
      #     #FileDataStoreFullPathOverride: 

  release:
    needs: [versioning, build]
    if: needs.versioning.outputs.release-exists == 'false'
      && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || inputs.push-preview == 'true')
    uses: f2calv/gha-workflows/.github/workflows/gha-release-versioning.yml@v1
    permissions:
      contents: write
    with:
      semVer: ${{ needs.versioning.outputs.version }}
      tag-prefix: ''
      move-major-tag: false
